name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: backend/
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-import-order
          pip install -r requirements.txt
      - name: Lint with flake8
        working-directory: backend/
        run: |
          flake8 .

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram:latest

  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file and compress tarball
      run: |
        touch .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo "DB_ENGINE=django.db.backends.postgresql" >> .env
        echo "DB_HOST=db" >> .env
        echo "DB_PORT=5432" >> .env
        echo "POSTGRES_DB=postgres" >> .env
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        cd ../
        tar -czf foodgram-project-react.tar.gz foodgram-project-react/
        mv foodgram-project-react.tar.gz foodgram-project-react/
    - name: Copying files via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "foodgram-project-react.tar.gz"
        target: "~"
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          tar -xzf foodgram-project-react.tar.gz
          cd foodgram-project-react/infra/
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/foodgram
          sudo docker-compose stop
          sudo docker-compose up -d
